# Site settings
title: FanLei Blog
SEOTitle: FanLei Blog
header-img: img/home-bg.png
email: 625768898@qq.com
description: 这里是 FanLei 的个人博客
keyword: FanLei,@FanLei
url: http://fanlei1130.github.io
baseurl: ''                                                # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: https://github.com/fanlei1130/fanlei1130.github.io.git  # you code repository

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username: FanLei
#zhihu_username: FanLei
github_username: fanlei1130
#jianshu_username: FanLei
#linkedin_username:
#twitter_username:
#facebook_username:

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - README.zh.md
anchorjs: true                       # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-paginate
  - jekyll-sitemap
b2t: true

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM


# Gitalk
#gitalk:
#  enable: true
#  clientID: xxxxxxxxxx
#  clientSecret: xxxxxxxxxxxxxx
#  repo: fanlei1130.github.io
#  owner: FanLei
#  admin: FanLei
#  distractionFreeMode: true


# Analytics settings
# Baidu Analytics
#ba_track_id: xxxxxxxxxxxxxxx

# Google Analytics
#ga_track_id: xxxxxxxxxx           # Format: UA-xxxxxx-xx
#ga_domain: xxxxxxxxxxxx

# Sidebar settings
sidebar: true                          # whether or not using Sidebar.
sidebar-about-description: 那些你很冒险的梦<br>我陪你去疯
sidebar-avatar: "/img/avatar-ny.jpg"


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 2              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: false

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  - title: Sitoi
    href: http://www.sitoi.cn
